### ISSUE TITLE
"pip3 install ." errors

### ISSUE THREAD

**Issue by alexandru-golub** [null3yte/mailhound#2]
Hi, I'm encountering the following error when trying to install. Any ideas what it could be? 

Building wheels for collected packages: mailhound
  Building wheel for mailhound (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib
      creating build/lib/mailhound
      copying mailhound/configs.py -> build/lib/mailhound
      copying mailhound/__init__.py -> build/lib/mailhound
      copying mailhound/__main__.py -> build/lib/mailhound
      creating build/lib/mailhound/Modules
      copying mailhound/Modules/sitemap.py -> build/lib/mailhound/Modules
      copying mailhound/Modules/__init__.py -> build/lib/mailhound/Modules
      creating build/lib/mailhound/Modules/Datasets
      copying mailhound/Modules/Datasets/Hunter.py -> build/lib/mailhound/Modules/Datasets
      copying mailhound/Modules/Datasets/__init__.py -> build/lib/mailhound/Modules/Datasets
      copying mailhound/Modules/Datasets/Snov.py -> build/lib/mailhound/Modules/Datasets
      copying mailhound/Modules/Datasets/Skymem.py -> build/lib/mailhound/Modules/Datasets
      copying mailhound/Modules/Datasets/Emailf.py -> build/lib/mailhound/Modules/Datasets
      copying mailhound/Modules/Datasets/Minelead.py -> build/lib/mailhound/Modules/Datasets
      running egg_info
      writing mailhound.egg-info/PKG-INFO
      writing dependency_links to mailhound.egg-info/dependency_links.txt
      writing entry points to mailhound.egg-info/entry_points.txt
      writing requirements to mailhound.egg-info/requires.txt
      writing top-level names to mailhound.egg-info/top_level.txt
      reading manifest file 'mailhound.egg-info/SOURCES.txt'
      adding license file 'LICENSE'
      writing manifest file 'mailhound.egg-info/SOURCES.txt'
      installing to build/bdist.macosx-10.9-universal2/wheel
      running install
      error: [Errno 2] No such file or directory: 'playwright'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mailhound
  Running setup.py clean for mailhound
Failed to build mailhound
ERROR: Could not build wheels for mailhound, which is required to install pyproject.toml-based projects

I'm running on macOS Ventura 13.5.1 - Intel processor.

**Comment by null3yte** [comment]
Check your Python version.
Playwright is only available for Python 3.7 and above

**Comment by alexandru-golub** [comment]
Alright, thank you. I’ll check it out with Python +3.7
